
CREATE TABLE USERS (
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL
    );

CREATE TABLE DVDS
(
    ID_DVD INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT,
    TITLE VARCHAR(256),
    TYPE VARCHAR(256),
    DESCRIPTION VARCHAR(256),
    EDITOR VARCHAR(256),
    AUDIO VARCHAR(256),
    RELEASEDATE VARCHAR(256),
    AGELIMIT INT,
    DURATION INT,
    RATING INT CHECK (RATING BETWEEN 0 AND 5),
    CONSTRAINT FK_USER FOREIGN KEY(ID_USER) REFERENCES USERS (ID_USER)

);

CREATE TABLE MOVIE_PEOPLE(
    ID_MOVIE_PEOPLE INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256)
                         );

CREATE TABLE DIRECTED_BY(
    MOVIE_ID INT,
    MOVIE_PERSON_ID INT,
    CONSTRAINT DIRECTED_BY_PK PRIMARY KEY(MOVIE_ID,MOVIE_PERSON_ID),
    CONSTRAINT FK_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES DVDS (ID_DVD),
    CONSTRAINT FK_MOVIE_PEOPLE FOREIGN KEY (MOVIE_PERSON_ID) REFERENCES MOVIE_PEOPLE (ID_MOVIE_PEOPLE)
);

CREATE TABLE VIDEOGAMES
(
    ID_VIDEO_GAME INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT,
    NAME VARCHAR(256),
    TYPE VARCHAR(256),
    RESUME VARCHAR(256),
    EDITOR VARCHAR(256),
    RELEASEDATE VARCHAR(256),
    EDITOR VARCHAR(256),
    RATING INT CHECK (RATING BETWEEN 0 AND 5),
    CONSTRAINT FK_USER FOREIGN KEY(ID_USER) REFERENCES USERS (ID_USER)
);

CREATE TABLE DEVELOPERS(
    ID_DEVELOPER INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256),
    LASTNAME VARCHAR(256)
);

CREATE TABLE DEVELOPPED_BY(
        VIDEO_GAME_ID INT,
        DEVELOPER_ID INT,
        CONSTRAINT DEVELOPED_BY_ID PRIMARY KEY(VIDEO_GAME_ID,DEVELOPER_ID),
        CONSTRAINT FK_VIDEO_GAME FOREIGN KEY (VIDEO_GAME_ID) REFERENCES VIDEOGAMES (ID_VIDEO_GAME),
        CONSTRAINT FK_DEVELOPER FOREIGN KEY (DEVELOPER_ID) REFERENCES DEVELOPERS (ID_DEVELOPER)
);

CREATE TABLE BOOKS
(
    ID_BOOK INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT,
    TITLE VARCHAR(256),
    TYPE VARCHAR(256),
    DESCRIPTION VARCHAR(256),
    RELEASEDATE VARCHAR(256),
    EDITOR VARCHAR(256),
    PLATEFORM VARCHAR(256),
    AGELIMIT INT,
    RATING INT CHECK (RATING BETWEEN 0 AND 5),
    CONSTRAINT FK_USER FOREIGN KEY(ID_USER) REFERENCES USERS (ID_USER)

);

CREATE TABLE AUTHORS(
     ID_AUTHOR INT PRIMARY KEY AUTO_INCREMENT,
     NAME VARCHAR(256)
                    );

CREATE TABLE WRITTEN_BY(
    BOOK_ID INT,
    AUTHOR_ID INT,
    CONSTRAINT WRITTEN_BY_ID PRIMARY KEY(BOOK_ID,AUTHOR_ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID_BOOK),
    CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID_AUTHOR)
);